# Generated by Django 4.2.3 on 2023-07-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255, unique=True, verbose_name='ID чата')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'чат',
                'verbose_name_plural': 'чаты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(unique=True, verbose_name='ID чата')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Username')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('can_basta', models.BooleanField(default=False, verbose_name='/basta')),
                ('can_ban', models.BooleanField(default=False, verbose_name='/ban*')),
                ('can_ban_all', models.BooleanField(default=False, verbose_name='/banall*')),
                ('can_mute', models.BooleanField(default=False, verbose_name='/mute*')),
                ('can_mute_all', models.BooleanField(default=False, verbose_name='/muteall*')),
            ],
            options={
                'verbose_name': 'администратор',
                'verbose_name_plural': 'администраторы',
            },
        ),
    ]
